name: Code Quality Checks

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main

jobs:
  checks:
    name: Run Code Checks and Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, xml, ctype, iconv, intl, xdebug, redis, mongodb, memcache, memcached
          coverage: xdebug
          tools: composer:v2

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-ci-${{ hashFiles('**/composer-ci.lock') }}
          restore-keys: ${{ runner.os }}-composer-ci-

      - name: Install dependencies (full set, with optional checker libs)
        env:
          COMPOSER: composer-ci.json
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Regenerate PHPStan baseline for CI environment
        run: make regenerate-baseline

      - name: Run checks
        run: make check

      - name: Run unit tests
        run: XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover=coverage.xml --log-junit junit.xml

      - name: Upload coverage to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
          flags: phpunit
          fail_ci_if_error: true
          slug: max-shamaev-php/healthcheck-bundle
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v5
        with:
          report_type: test_results
          flags: phpunit
          fail_ci_if_error: true
          slug: max-shamaev-php/healthcheck-bundle
          token: ${{ secrets.CODECOV_TOKEN }}
